// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/trips/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trips/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trips/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trips/[id].put').default>>>>
    }
    '/api/trips': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trips/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trips/index.post').default>>>>
    }
    '/api/trips/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trips/search.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}