// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/19/2025, 5:17:16 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/fish-uncle/Desktop/未命名文件夹/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fish-uncle/Desktop/未命名文件夹/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fish-uncle/Desktop/未命名文件夹/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fish-uncle/Desktop/未命名文件夹/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fish-uncle/Desktop/未命名文件夹/plugins/**/*.{js,ts,mjs}","/Users/fish-uncle/Desktop/未命名文件夹/composables/**/*.{js,ts,mjs}","/Users/fish-uncle/Desktop/未命名文件夹/utils/**/*.{js,ts,mjs}","/Users/fish-uncle/Desktop/未命名文件夹/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/fish-uncle/Desktop/未命名文件夹/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/fish-uncle/Desktop/未命名文件夹/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/fish-uncle/Desktop/未命名文件夹/app.config.{js,ts,mjs}","/Users/fish-uncle/Desktop/未命名文件夹/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;